<?php $accordionhtml = "$( '#accordion' ).accordion();" ?>

<?php include('header.php') ?>
<?php
    $file_handle = fopen("vars.txt", "r");
    $result = array();
    while (!feof($file_handle) ) {
        $line_of_text = fgets($file_handle);
        $parts = explode(':', trim($line_of_text), 2);
        ${strtolower($parts[0])} = trim($parts[1]);
    }

    fclose($file_handle);
?>
<script>
    $(function() {
        $("#libatch").attr('class', 'active');
    });
</script>
<div class="container wrap section" style="margin-top: 51px">
    <h1>Batch Numbers</h1>
    <div class="panel">
        <img src="images/online.png" height="150" style="margin-bottom: 30px">
        <div class="title" align="center">
            <h3>Check your batch number here: <a href="https://reg-system-server.herokuapp.com" target="_blank">Ateneo Student Manual Registration System</a></h3><!--font color="red">(The system is currently under maintenance. Please stand by for announcements)</font--><br>
            <p>*Graduate students and undergraduate international exchange students do not have batching.<br>
                 *The batch numbers are generated by the <strong>Office of MIS</strong>.<br><br>
             </p>
            <h3><u>How to Use the System</u> <br>(For Undergraduates, International Exchange, and Graduates)</h3>
            <ol style="max-width: 450px; margin:0 auto; text-align:left; ">
                <li>Go to <a href="http://bit.ly/ManualRegSystem" target="_blank">http://bit.ly/ManualRegSystem</a> or click the link above.</li>
				<li>Enter your ID number and password. <br>For all users:
					<ul style = "list-style: none;">	
						<li class = "indent">Password: <font color="blue">IDNUMBER</font>LASTNAME</li>
						<li class = "indent">NOTE: Your last name should be in all caps. Use N instead of Ñ.</li>
						<li class = "indent">Include special characters, roman numerals and space in last name if present. (E.G. 201819DE LOS SANTOS II)</li> 
						<li class = "indent">Read the privacy notice before clicking "Accept".</li>
					</ul>
				</li>
                <li>Go to the 3rd tab and change your password.</li>
                <li>Go to "Update Problem/s" Tab and input all enlistment problems.</li>
					<ul style = "list-style: none;"">	
						<li class = "indent"><strong>Format:</strong> Problem #: course code, details.<br></li>
						<li class = "indent"><strong>Example:</strong> Problem 1: MA21, ran out of slots.</li>
						<li class = "indent">NOTE: Students are strongly encouraged to input their problems days <strong>BEFORE</strong> manual registration.</li>
					</ul>
				</li>
				<li>Click "Submit" and a confirmation window will appear. Then, log out.</li>
                <li>Contact <a href="https://www.facebook.com/RegComHelpdesk">RegCom's Helpdesk</a> if you encounter any problems in using the system.</li>
            </ol>
        </div>
    </div>
</div>
<!--<div class="container wrap section" style="margin-top:51px;">
    <h1>Batch Numbers</h1>-->
    <!--<div id="app">
        <div class="id_input">Enter ID Number</div>
        <input id='id_input' class="wrap" type='text' placeholder='Enter your ID number here'/>
        <br>
        <label class="online">Online Registration Batch Number</label>
        <input id='online' class="wrap" type='text' readonly />
        <br>
        <label class="manual">Manual Registration Batch Number</label>
        <input id='manual' class="wrap" type='text' readonly />
        <br>
        <label class="semester">Semester</label>
        <input id='semester' class="wrap" type='text' readonly />
        <br>
        <label class="name">Name</label>
        <input id='name' class="wrap" type='text' readonly />
        <br>
        <label class="year">Year</label>
        <input id='year' class="wrap" type='text' readonly />
        <br>
        <label class="course">Course</label>
        <input id='course' class="wrap" type='text' readonly />
        <button id="search">Search</button>
        <div style="clear:both"></div>
        <p class="detail">
            How to use the app:<br>
            Enter your Ateneo ID Number on the box above and press enter. <br><br>

            Note:<br>
            Graduate students <strong>do not have batching.</strong><br>The batch numbers are generated by the <strong>Office of MIS.</strong> <br><br>

            <center>
            <h3 name="notdisplaying">Batch Number Not Displaying?</h2>
            <h4>Try these steps:</h3>
            </center>
            <ol style="text-align: left;">
                <li>Refresh your browser.</li>
                <li>Use Incognito Mode.</li>
                <li>Clear your cache. The old website might still be stored in your computer's cache. For more details, click <a href ="http://www.refreshyourcache.com/en/home/">here</a>.</li>
                <li><strong>Coming from LOA?</strong> Please contact the Registrar's Office for your batch number.</li>
                <li>If all else fails, please contact us at <a href="https://www.facebook.com/RegComHelpdesk">Regcom’s Helpdesk</a>.</li>
            </ol>

        </p>
    </div>
</div>-->
<div id="eta" class="container section wrap" style="margin-top: 1px; padding-top:1px;">
    <h1>Expected Times of Arrivals</h1>
    <h3>Undergraduate Level and Graduate Level:<br>Batching Schedule</h3>
    <p><center><?php echo $semester ?></center></p>
    <h3 class="title">Aisis Online Enlistment Schedule</h3>
    <table>
        <thead>
            <tr>
                <td colspan="2">Online Enlistment Dates</td>
            </tr>
        </thead>
        <tbody>
        	<!-- Regular Sem -->
			
            <!--tr>
                <td><?php echo $dateseniorsonline ?></td>
                <td>Seniors and Superseniors</td>
            </tr>
            <tr>
                <td><?php echo $datejuniorsonline ?></td>
                <td>Juniors and Undergraduate Int'l Exchange Students</td>
            </tr>
            <tr>
                <td><?php echo $datesophomoresonline ?></td>
                <td>Sophomores</td>
            </tr>
            <tr>
                <td><?php echo $datefreshmenonline ?></td>
                <td>Freshmen</td>
            </tr-->

        	<!-- Intersession -->
             <tr>
                <td><?php echo $dateinteronlineday1 ?></td>
                <td>Undergraduates <strong> required </strong> to take Intersession classes, and Graduate students</td>
            </tr>
             <tr>
                <td><?php echo $dateinteronlineday2 ?></td>
                <td>Undergraduates <strong> required </strong> and <strong> not required </strong> to take Intersession classes, and Graduate students</td>
            </tr>
        </tbody>
    </table>
    <table>
        <thead>
            <tr>
                <td colspan="2">Online Enlistment Batch Schedule</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="subtitle">Batch</td>
                <td class="subtitle">Date and Time</td>
            </tr>

            <!-- Regular Sem -->
            <!--tr>
                <td>1</td>
                <td><?php echo $timebatchone ?></td>
            </tr>
            <tr>
                <td>2</td>
                <td><?php echo $timebatchtwo ?></td>
            </tr -->
            <!-- Graduates -->
            <tr>
                <td>Graduates</td>
                
                <td>
                    <?php echo $dategradonline ?>
                    <br>
                    <?php echo $timegradonline ?>
                </td>
            </tr>
            <!--Exchange students>
            <tr>
                <td>Undergraduate Int'l Exchange Students</td>
                <td><?php echo $timeintlonline ?></td>
            </tr -->


            <!-- Intersession -->
            < <tr>
                <td>1</td>
                <td><?php echo $dateinteronlineday1 ?><br>
                    9:00 am - 12:00 pm</td>
            </tr>
            <tr>
                <td>2</td>
                <td><?php echo $dateinteronlineday1 ?><br>
                   1:00 pm - 4:00 pm</td>
            </tr>
            <tr>
                <td>3</td>
                <td><?php echo $dateinteronlineday2 ?><br>
                    9:00 am - 12:00 pm</td>
            </tr>
            <tr>
                <td>4</td>
                <td><?php echo $dateinteronlineday2 ?><br>
                    1:00 pm - 4:00 pm</td>
            </tr>

            <!-- Free for All -->
            <tr>
                <td>Free-for-all</td>
                <td>
                        <!-- Intersession Only -->
                    <!-- <?php echo $dateinteronlineday2 ?> -->
                        <!-- Regular Sem -->
                    <?php echo $dateffaonline ?>
                    <br>
                    <?php echo $timeffaonline ?>
                </td>
            </tr>

        </tbody>
    </table>

    <h3 class="title">Manual Enlistment Schedule</h3>
    <table>
        <thead>
            <tr>
                <td colspan="2">Manual Registration Dates</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="subtitle">Date</td>
                <td class="subtitle">Year Level</td>
            </tr>
			
            <!--tr>
                <td><?php echo $datesophseniorsmanreg ?></td>
                <td>Sophomores, Seniors, and Superseniors</td>
            </tr>

            <tr>
                <td><?php echo $datejuniorsmanreg ?></td>
                <td>Juniors</td>
            </tr -->
			
            <tr>
                <td><?php echo $dateintermanualday1 ?></td>
                <td>All Year Levels (Batching Applies)</td>
            </tr>
             <tr>
                <td><?php echo $dateintermanualday2 ?></td>
                <td>All Year Levels (Free-for-all)</td>
            </tr>

            <tr>
                <td><?php echo $dategradmanreg ?></td>
                <td>Graduates</td>
            </tr>
            
            <!--tr>
                <td><?php echo $dateintlmanreg ?></td>
                <td>Undergraduate Int'l Exchange Students</td>
            </tr>
			
            <tr>
                <td><?php echo $datefreshmanreg ?></td>
                <td>Freshmen</td>
            </tr>

			<tr>
                <td><?php echo $dateffamanreg ?></td>
                <td>All Year Levels (Free-For-All)</td>
            </tr-->
           
        </tbody>
    </table>
<!--<p class="detail">
    *Manual Registration for January 16 will be from 8:00 am - 12:00 nn <strong>ONLY</strong>
</p>-->

    <h3 class="title">Expected Time of Arrival (ETA) and Venue</h3>
    <table>
        <thead>
            <tr>
                <td colspan="2">Manual Registration Expected Time of Arrival (ETA) </td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="subtitle">Batch in Manual Enlistment</td>
                <td class="subtitle">Time</td>
            </tr>
            <tr>
                <td>1</td>
                <td>8:00 am - 10:00 am</td>
            </tr>
            <tr>
                <td>2</td>
                <td>10:00 am - 12:00 nn</td>
            </tr>
            <tr>
                <td>3</td>
                <td>1:00 pm - 2:00 pm</td>
            </tr>
            <tr>
                <td>4</td>
                <td>2:00 pm - 3:00 pm</td>
            </tr>
            <tr>
                <td>Free-for-all</td>
                <td>3:00 pm - 4:00 pm</td>
            </tr>
        </tbody>
    </table>
    <table>
        <thead>
            <tr>
                <td colspan="2">Waiting Area</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="subtitle">School</td>
                <td class="subtitle">Venue (Waiting Area)</td>
            </tr>
            <tr>
                <td>SOH and SOSS</td>
                <td><strong><?php echo $sohsosswaitvenue ?></strong></td>
            </tr>
            <tr>
                <td>SOM</td>
                <td><strong><?php echo $somwaitvenue ?></strong></td>
            </tr>
            <tr>
                <td>SOSE</td>
                <td><strong><?php echo $sosewaitvenue ?></strong></td>
            </tr>
			<tr>
                <td>Special Students**</td>
                <td><strong><?php echo $specialwaitvenue ?></strong></td>
            </tr>
            <tr>
                <td>Graduate Students</td>
                <td><strong><?php echo $checkersvenue ?></strong></td>
            </tr>
        </tbody>
    </table>
    <p class="detail">
        <!--*Manual Registration for <?php echo $dateffamanreg ?> will be from <?php echo $sathours ?> ONLY <br>-->
        **Special students include cross-registrants, auditors, and non-degree students<br>
        For inquiries, drop us a line on our Facebook page, <a href="https://www.facebook.com/RegComHelpdesk">Regcom’s Helpdesk</a>.
    </p>
</div>

<script type="text/javascript">
    function toggle_visibility(id) {
       var e = document.getElementById(id);
       if(e.style.display == 'block')
          e.style.display = 'none';
       else
          e.style.display = 'block';
    }
</script>
<script>
/***************************************************************************/
/*                                                                         */
/*  This obfuscated code was created by Javascript Obfuscator Free Version.*/
/*  Javascript Obfuscator Free Version can be downloaded here              */
/*  http://javascriptobfuscator.com                                        */
/*                                                                         */
/***************************************************************************/
var _$_d4be=["\x76\x61\x6C","\x23\x69\x64\x5F\x69\x6E\x70\x75\x74","\x64\x61\x74\x61\x2F\x31\x32\x30\x30\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x32\x32\x35\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x33\x30\x30\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x33\x32\x35\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x33\x35\x30\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x34\x30\x30\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x34\x32\x35\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x34\x35\x30\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x35\x30\x30\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x35\x32\x35\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x35\x35\x30\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x36\x30\x30\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x36\x32\x35\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x37\x30\x30\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x31\x37\x32\x35\x30\x30\x2E\x63\x73\x76","\x64\x61\x74\x61\x2F\x6F\x74\x68\x65\x72\x73\x2E\x63\x73\x76","\x68\x74\x6D\x6C","\x6C\x6F\x67","\x0A","\x73\x70\x6C\x69\x74","\x6C\x65\x6E\x67\x74\x68","\x2C","\x23\x6F\x6E\x6C\x69\x6E\x65","\x23\x6D\x61\x6E\x75\x61\x6C","\x23\x6E\x61\x6D\x65","\x23\x63\x6F\x75\x72\x73\x65","\x23\x79\x65\x61\x72","\x23\x73\x65\x6D\x65\x73\x74\x65\x72","\x49\x44\x20\x6E\x75\x6D\x62\x65\x72\x20\x6E\x6F\x74\x20\x66\x6F\x75\x6E\x64","\x67\x65\x74","\x63\x6C\x69\x63\x6B","\x23\x73\x65\x61\x72\x63\x68","\x77\x68\x69\x63\x68","\x6B\x65\x79\x70\x72\x65\x73\x73","\x24","\x70\x72\x65\x76\x65\x6E\x74\x44\x65\x66\x61\x75\x6C\x74","\x73\x75\x62\x6D\x69\x74","\x72\x65\x61\x64\x79"];$(document)[_$_d4be[39]](function(){$(_$_d4be[33])[_$_d4be[32]](function(){var _0x3725;if($(_$_d4be[1])[_$_d4be[0]]()>= 120000&& $(_$_d4be[1])[_$_d4be[0]]()< 122500){_0x3725= _$_d4be[2]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 122500&& $(_$_d4be[1])[_$_d4be[0]]()< 125000){_0x3725= _$_d4be[3]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 130000&& $(_$_d4be[1])[_$_d4be[0]]()< 132500){_0x3725= _$_d4be[4]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 132500&& $(_$_d4be[1])[_$_d4be[0]]()< 135000){_0x3725= _$_d4be[5]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 135000&& $(_$_d4be[1])[_$_d4be[0]]()< 137500){_0x3725= _$_d4be[6]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 140000&& $(_$_d4be[1])[_$_d4be[0]]()< 142500){_0x3725= _$_d4be[7]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 142500&& $(_$_d4be[1])[_$_d4be[0]]()< 145000){_0x3725= _$_d4be[8]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 145000&& $(_$_d4be[1])[_$_d4be[0]]()< 147500){_0x3725= _$_d4be[9]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 150000&& $(_$_d4be[1])[_$_d4be[0]]()< 152500){_0x3725= _$_d4be[10]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 152500&& $(_$_d4be[1])[_$_d4be[0]]()< 155000){_0x3725= _$_d4be[11]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 155000&& $(_$_d4be[1])[_$_d4be[0]]()< 157500){_0x3725= _$_d4be[12]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 160000&& $(_$_d4be[1])[_$_d4be[0]]()< 162500){_0x3725= _$_d4be[13]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 162500&& $(_$_d4be[1])[_$_d4be[0]]()< 165000){_0x3725= _$_d4be[14]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 170000&& $(_$_d4be[1])[_$_d4be[0]]()< 172500){_0x3725= _$_d4be[15]}else {if($(_$_d4be[1])[_$_d4be[0]]()>= 172500&& $(_$_d4be[1])[_$_d4be[0]]()< 175000){_0x3725= _$_d4be[16]}else {_0x3725= _$_d4be[17]}}}}}}}}}}}}}}};$[_$_d4be[31]](_0x3725,{language:_$_d4be[18],version:5},function(_0x380F){var _0x3836= new String(_0x380F);console[_$_d4be[19]](_0x3836);var _0x374C= new Array();_0x374C= _0x3836[_$_d4be[21]](_$_d4be[20]);var _0x37E8=_0x374C[_$_d4be[22]],_0x3773=null;var _0x379A=false;for(var _0x37C1=0;_0x37C1< _0x37E8;_0x37C1++){_0x3773= _0x374C[_0x37C1];tempStudent= _0x3773[_$_d4be[21]](_$_d4be[23]);_0x374C[_0x37C1]= tempStudent;if(tempStudent[0]== $(_$_d4be[1])[_$_d4be[0]]()){_0x379A= true;$(_$_d4be[24])[_$_d4be[0]](tempStudent[1]);$(_$_d4be[25])[_$_d4be[0]](tempStudent[2]);$(_$_d4be[26])[_$_d4be[0]](tempStudent[3]+ _$_d4be[23]+ tempStudent[4]);$(_$_d4be[27])[_$_d4be[0]](tempStudent[5]);$(_$_d4be[28])[_$_d4be[0]](tempStudent[6]);$(_$_d4be[29])[_$_d4be[0]](tempStudent[7])}};if(_0x379A== false){alert(_$_d4be[30])}},_$_d4be[18])});$(_$_d4be[1])[_$_d4be[35]](function(_0x385D){if(_0x385D[_$_d4be[34]]== 13){$(_$_d4be[33])[_$_d4be[32]]()}});$(_$_d4be[1])[_$_d4be[38]](function(){event[_$_d4be[37]]()[_$_d4be[36]](_$_d4be[33])[_$_d4be[32]]()})})
</script>

<?php include('footer.php') ?>